wide_resnet50_2:
- wide_resnet50_2_layer1: 4
- wide_resnet50_2_layer2: 4
- wide_resnet50_2_layer3: 4
- wide_resnet50_2_layer4: 4
- wide_resnet50_2_layer5: 4
- wide_resnet50_2_layer6: 4
- wide_resnet50_2_layer7: 4
- wide_resnet50_2_layer8: 4
- wide_resnet50_2_layer9: 4
- wide_resnet50_2_layer10: 4
- wide_resnet50_2_layer11: 4
- wide_resnet50_2_layer12: 4
- wide_resnet50_2_layer13: 4
- wide_resnet50_2_layer14: 4
- wide_resnet50_2_layer15: 4
- wide_resnet50_2_layer16: 4
- wide_resnet50_2_layer17: 4
- wide_resnet50_2_layer18: 4
- wide_resnet50_2_layer19: 4
- wide_resnet50_2_layer20: 4
- wide_resnet50_2_layer21: 4
- wide_resnet50_2_layer22: 4
- wide_resnet50_2_layer23: 4
- wide_resnet50_2_layer24: 4
- wide_resnet50_2_layer25: 4
- wide_resnet50_2_layer26: 4
- wide_resnet50_2_layer27: 4
- wide_resnet50_2_layer28: 4
- wide_resnet50_2_layer29: 4
- wide_resnet50_2_layer30: 4
- wide_resnet50_2_layer31: 4
- wide_resnet50_2_layer32: 4
- wide_resnet50_2_layer33: 4
- wide_resnet50_2_layer34: 4
- wide_resnet50_2_layer35: 4
- wide_resnet50_2_layer36: 4
- wide_resnet50_2_layer37: 4
- wide_resnet50_2_layer38: 4
- wide_resnet50_2_layer39: 4
- wide_resnet50_2_layer40: 4
- wide_resnet50_2_layer41: 4
- wide_resnet50_2_layer42: 4
- wide_resnet50_2_layer43: 4
- wide_resnet50_2_layer44: 4
- wide_resnet50_2_layer45: 4
- wide_resnet50_2_layer46: 4
- wide_resnet50_2_layer47: 4
- wide_resnet50_2_layer48: 4
- wide_resnet50_2_layer49: 4
- wide_resnet50_2_layer50: 4
- wide_resnet50_2_layer51: 4
- wide_resnet50_2_layer52: 4
- wide_resnet50_2_layer53: 4
- wide_resnet50_2_layer54: 4
- wide_resnet50_2_layer55: 4
- wide_resnet50_2_layer56: 4
- wide_resnet50_2_layer57: 4
- wide_resnet50_2_layer58: 4
- wide_resnet50_2_layer59: 4
- wide_resnet50_2_layer60: 4
- wide_resnet50_2_layer61: 4
- wide_resnet50_2_layer62: 4
- wide_resnet50_2_layer63: 4
- wide_resnet50_2_layer64: 4
